-- Indiana Beverage brand catalog, from indianabev.com/completeportfolio (October 2026).
-- Their site calls this "some of the most popular" of 90+ brewery partners, so it is not exhaustive.
-- Add or fix rows anytime in Table Editor > partner_brands.

alter table public.partner_brands add column if not exists aliases text[] not null default '{}';

-- True when a typed brand is one Indiana Beverage carries: exact name, or a whole-word alias match
create or replace function public.is_partner_brand(b text, p text default 'indianabev')
returns boolean language sql stable security invoker set search_path = '' as $$
  select exists (
    select 1 from public.partner_brands pb
    where pb.partner = p and pb.active and (
      lower(pb.name) = lower(trim(b))
      or exists (
        select 1 from unnest(pb.aliases) a
        where lower(b) ~ ('\m' || regexp_replace(a, '([.^$*+?()[\]{}|\\-])', '\\\1', 'g') || '\M')
      )
    )
  );
$$;
grant execute on function public.is_partner_brand(text, text) to authenticated;

insert into public.partner_brands (partner, name, category, aliases) values
('indianabev', 'Coors Banquet', null, array['coors banquet']::text[]),
('indianabev', 'Coors Light', 'Light Lager', array['coors light']::text[]),
('indianabev', 'Hamm''s', null, array['hamm''s']::text[]),
('indianabev', 'Icehouse', null, array['icehouse']::text[]),
('indianabev', 'Keystone Light', 'Light Lager', array['keystone light']::text[]),
('indianabev', 'Miller Genuine Draft', null, array['miller genuine draft']::text[]),
('indianabev', 'Miller 64', 'Light Lager', array['miller 64']::text[]),
('indianabev', 'Miller High Life', null, array['miller high life']::text[]),
('indianabev', 'Miller Lite', 'Light Lager', array['miller lite']::text[]),
('indianabev', 'Milwaukee''s Best', null, array['milwaukee''s best']::text[]),
('indianabev', 'Old Milwaukee', null, array['old milwaukee']::text[]),
('indianabev', 'Old Style', null, array['old style']::text[]),
('indianabev', 'Pabst Blue Ribbon', null, array['pabst blue ribbon','pbr']::text[]),
('indianabev', 'Stroh''s', null, array['stroh''s']::text[]),
('indianabev', 'Yuengling', null, array['yuengling']::text[]),
('indianabev', '18th Street Brewery', null, array['18th street','18th street brewery']::text[]),
('indianabev', 'Abita Brewing', null, array['abita','abita brewing']::text[]),
('indianabev', 'Anchor Brewing', null, array['anchor','anchor brewing']::text[]),
('indianabev', 'Bell''s Brewing', null, array['bell''s','bell''s brewing','oberon','two hearted']::text[]),
('indianabev', 'Blue Moon Brewing', null, array['blue moon','blue moon brewing']::text[]),
('indianabev', 'Boulevard Brewing', null, array['boulevard','boulevard brewing']::text[]),
('indianabev', 'Chapman''s Brewing', 'Local craft', array['chapman''s','chapman''s brewing']::text[]),
('indianabev', 'Cigar City Brewing', null, array['cigar city','cigar city brewing']::text[]),
('indianabev', 'Dark Horse Brewing', null, array['dark horse','dark horse brewing']::text[]),
('indianabev', 'Deschutes Brewery', null, array['black butte','deschutes','deschutes brewery','fresh squeezed']::text[]),
('indianabev', 'Dogfish Head', null, array['dogfish head']::text[]),
('indianabev', 'Epic Brewing', null, array['epic brewing']::text[]),
('indianabev', 'Evil Czech Brewery', 'Local craft', array['evil czech','evil czech brewery']::text[]),
('indianabev', 'Firestone Walker Brewing', null, array['805','firestone walker','firestone walker brewing']::text[]),
('indianabev', 'Four Sixes', null, array['four sixes']::text[]),
('indianabev', 'Greenbush Brewing', null, array['greenbush','greenbush brewing']::text[]),
('indianabev', 'Half Acre Beer', null, array['daisy cutter','half acre','half acre beer']::text[]),
('indianabev', 'Jolly Pumpkin Artisan Ales', null, array['jolly pumpkin','jolly pumpkin artisan ales']::text[]),
('indianabev', 'Lagunitas Brewing', null, array['lagunitas','lagunitas brewing']::text[]),
('indianabev', 'Leinenkugel''s', null, array['leinenkugel''s']::text[]),
('indianabev', 'Man Cave Brewing', null, array['man cave','man cave brewing']::text[]),
('indianabev', 'New Belgium Brewing', null, array['fat tire','new belgium','new belgium brewing','voodoo ranger']::text[]),
('indianabev', 'New Holland Brewing', null, array['new holland','new holland brewing']::text[]),
('indianabev', 'New Oberpfalz Brewing', 'Local craft', array['new oberpfalz','new oberpfalz brewing']::text[]),
('indianabev', 'North Coast Brewing', null, array['north coast','north coast brewing']::text[]),
('indianabev', 'Octopi Brewing', null, array['octopi','octopi brewing']::text[]),
('indianabev', 'Odd Side Ales', null, array['odd side','odd side ales']::text[]),
('indianabev', 'Ommegang Brewery', null, array['ommegang','ommegang brewery']::text[]),
('indianabev', 'Oskar Blues Brewery', null, array['dale''s pale ale','oskar blues','oskar blues brewery']::text[]),
('indianabev', 'Pipeworks Brewing', null, array['pipeworks','pipeworks brewing']::text[]),
('indianabev', 'Revolution Brewing', null, array['anti-hero','revolution','revolution brewing']::text[]),
('indianabev', 'Samuel Adams', null, array['sam adams','samuel adams']::text[]),
('indianabev', 'Shiner', null, array['shiner']::text[]),
('indianabev', 'Shoreline Brewery', 'Local craft', array['shoreline','shoreline brewery']::text[]),
('indianabev', 'Sierra Nevada Brewing', null, array['sierra nevada','sierra nevada brewing']::text[]),
('indianabev', 'Solemn Oath Brewery', null, array['solemn oath','solemn oath brewery']::text[]),
('indianabev', 'Southern Tier Brewing', null, array['pumking','southern tier','southern tier brewing']::text[]),
('indianabev', 'Sun King Brewery', 'Local craft', array['sun king','sun king brewery','wee mac']::text[]),
('indianabev', 'SweetWater Brewing', null, array['sweetwater','sweetwater brewing']::text[]),
('indianabev', 'Terrapin Beer', null, array['terrapin','terrapin beer']::text[]),
('indianabev', 'Three Floyds Brewing', 'Local craft', array['3 floyds','alpha king','gumballhead','three floyds','three floyds brewing','zombie dust']::text[]),
('indianabev', 'Two Brothers Artisan Brewing', null, array['two brothers','two brothers artisan brewing']::text[]),
('indianabev', 'Upland Brewing', 'Local craft', array['upland','upland brewing']::text[]),
('indianabev', 'Victory Brewing', null, array['victory','victory brewing']::text[]),
('indianabev', 'WarPigs Brewing', null, array['warpigs','warpigs brewing']::text[]),
('indianabev', '99 Brand', 'Other', array['99 brand']::text[]),
('indianabev', 'Arnold Palmer Spiked', 'Other', array['arnold palmer spiked']::text[]),
('indianabev', 'Bravazzi Hard Italian Soda', 'Other', array['bravazzi hard italian soda']::text[]),
('indianabev', 'Cayman Jack', 'Other', array['cayman jack']::text[]),
('indianabev', 'Corona Refresca', 'Other', array['corona refresca']::text[]),
('indianabev', 'Fireball Cinnamon', 'Other', array['fireball cinnamon']::text[]),
('indianabev', 'Four Loko', 'Other', array['four loko']::text[]),
('indianabev', 'Henry''s Hard Soda', 'Other', array['henry''s hard soda']::text[]),
('indianabev', 'Jack Daniel''s Country Cocktails', 'Other', array['jack daniel''s country cocktails']::text[]),
('indianabev', 'Jim Beam Kentucky Coolers', 'Other', array['jim beam kentucky coolers']::text[]),
('indianabev', 'Joose', 'Other', array['joose']::text[]),
('indianabev', 'Malibu Splash', 'Other', array['malibu splash']::text[]),
('indianabev', 'Mike''s Hard Lemonade', 'Other', array['mike''s hard lemonade']::text[]),
('indianabev', 'MXD Cocktail', 'Other', array['mxd cocktail']::text[]),
('indianabev', 'Not Your Father''s', 'Other', array['not your father''s']::text[]),
('indianabev', 'Parrot Bay', 'Other', array['parrot bay']::text[]),
('indianabev', 'Pirate Water', 'Other', array['pirate water']::text[]),
('indianabev', 'Rebel Hard Coffee', 'Other', array['rebel hard coffee']::text[]),
('indianabev', 'Redd''s Hard Apple', 'Other', array['redd''s hard apple']::text[]),
('indianabev', 'Sauza Agave Cocktails', 'Other', array['sauza agave cocktails']::text[]),
('indianabev', 'Seagram''s Escapes', 'Other', array['seagram''s escapes']::text[]),
('indianabev', 'Simply Spiked Lemonade', 'Other', array['simply spiked lemonade']::text[]),
('indianabev', 'Smirnoff Ice', 'Other', array['smirnoff ice']::text[]),
('indianabev', 'Southern Comfort', 'Other', array['southern comfort']::text[]),
('indianabev', 'Twisted Tea', 'Other', array['twisted tea']::text[]),
('indianabev', 'Colt 45', 'Other', array['colt 45']::text[]),
('indianabev', 'Genesee', 'Other', array['genesee']::text[]),
('indianabev', 'Little Kings', 'Other', array['little kings']::text[]),
('indianabev', 'Mickey''s Malt Liquor', 'Other', array['mickey''s malt liquor']::text[]),
('indianabev', 'Olde English', 'Other', array['olde english']::text[]),
('indianabev', 'St. Ide''s', 'Other', array['st. ide''s']::text[]),
('indianabev', 'Steel Reserve', 'Other', array['steel reserve']::text[]),
('indianabev', 'Angry Orchard', 'Other', array['angry orchard']::text[]),
('indianabev', 'Magners Irish Cider', 'Other', array['magners irish cider']::text[]),
('indianabev', 'Strongbow', 'Other', array['strongbow']::text[]),
('indianabev', 'Vander Mill', 'Other', array['vander mill']::text[]),
('indianabev', 'Woodchuck', 'Other', array['woodchuck']::text[]),
('indianabev', 'Wyder''s', 'Other', array['wyder''s']::text[]),
('indianabev', 'Black Dragon Meadery', 'Other', array['black dragon meadery']::text[]),
('indianabev', 'Libby', 'Other', array['libby']::text[]),
('indianabev', 'Running Vines Winery', 'Other', array['running vines winery']::text[]),
('indianabev', 'Simply Fruit', 'Other', array['simply fruit']::text[]),
('indianabev', 'Sol de Ibiza Sangria', 'Other', array['sol de ibiza sangria']::text[]),
('indianabev', 'Swashbuckler', 'Other', array['swashbuckler']::text[]),
('indianabev', 'Alfa', 'Import', array['alfa']::text[]),
('indianabev', 'Amstel Light', 'Import', array['amstel light']::text[]),
('indianabev', 'Asahi', 'Import', array['asahi']::text[]),
('indianabev', 'Ayinger', 'Import', array['ayinger']::text[]),
('indianabev', 'Big Deal Brewing', 'Import', array['big deal','big deal brewing']::text[]),
('indianabev', 'Chouffe', 'Import', array['chouffe']::text[]),
('indianabev', 'Corona', 'Import', array['corona']::text[]),
('indianabev', 'Daura Damm', 'Import', array['daura damm']::text[]),
('indianabev', 'Dos Equis', 'Import', array['dos equis']::text[]),
('indianabev', 'Duvel', 'Import', array['duvel']::text[]),
('indianabev', 'Foster''s', 'Import', array['foster''s']::text[]),
('indianabev', 'Green''s Gluten Free', 'Import', array['green''s gluten free']::text[]),
('indianabev', 'Grolsch', 'Import', array['grolsch']::text[]),
('indianabev', 'Guinness', 'Import', array['guinness']::text[]),
('indianabev', 'Hacker-Pschorr', 'Import', array['hacker pschorr','hacker-pschorr']::text[]),
('indianabev', 'Harp Lager', 'Import', array['harp lager']::text[]),
('indianabev', 'Heineken', 'Import', array['heineken']::text[]),
('indianabev', 'Labatt Blue', 'Import', array['labatt blue']::text[]),
('indianabev', 'Lefebvre', 'Import', array['lefebvre']::text[]),
('indianabev', 'Lindemans', 'Import', array['lindeman''s','lindemans']::text[]),
('indianabev', 'Lucky Buddha', 'Import', array['lucky buddha']::text[]),
('indianabev', 'Modelo Especial', 'Import', array['modelo especial']::text[]),
('indianabev', 'Molson Canadian', 'Import', array['molson canadian']::text[]),
('indianabev', 'Moosehead Lager', 'Import', array['moosehead lager']::text[]),
('indianabev', 'Murphy''s Stout', 'Import', array['murphy''s stout']::text[]),
('indianabev', 'Newcastle Brown Ale', 'Import', array['newcastle brown ale']::text[]),
('indianabev', 'Orval Trappist Ale', 'Import', array['orval trappist ale']::text[]),
('indianabev', 'Pacifico', 'Import', array['pacifico']::text[]),
('indianabev', 'Peroni', 'Import', array['peroni']::text[]),
('indianabev', 'Pilsner Urquell', 'Import', array['pilsner urquell']::text[]),
('indianabev', 'Red Stripe', 'Import', array['red stripe']::text[]),
('indianabev', 'Samuel Smith', 'Import', array['samuel smith']::text[]),
('indianabev', 'Sapporo', 'Import', array['sapporo']::text[]),
('indianabev', 'Singha', 'Import', array['singha']::text[]),
('indianabev', 'Smithwick''s Red Ale', 'Import', array['smithwick''s red ale']::text[]),
('indianabev', 'Sol Cerveza', 'Import', array['sol','sol cerveza']::text[]),
('indianabev', 'Tecate', 'Import', array['tecate']::text[]),
('indianabev', 'Trappistes Rochefort', 'Import', array['trappistes rochefort']::text[]),
('indianabev', 'Tsingtao', 'Import', array['tsingtao']::text[]),
('indianabev', 'Tyskie', 'Import', array['tyskie']::text[]),
('indianabev', 'Unibroue', 'Import', array['unibroue']::text[]),
('indianabev', 'Victoria Cerveza', 'Import', array['victoria','victoria cerveza']::text[]),
('indianabev', 'Warsteiner', 'Import', array['warsteiner']::text[]),
('indianabev', 'Westmalle Trappist', 'Import', array['westmalle trappist']::text[]),
('indianabev', 'Zywiec', 'Import', array['zywiec','żywiec']::text[]),
('indianabev', 'Alani Seltz', 'Seltzer', array['alani seltz']::text[]),
('indianabev', 'City Water', 'Seltzer', '{}'::text[]),
('indianabev', 'Corona Hard Seltzer', 'Seltzer', array['corona','corona hard seltzer']::text[]),
('indianabev', 'Crook & Marker', 'Seltzer', array['crook & marker']::text[]),
('indianabev', 'Dos Equis Ranch Water', 'Seltzer', array['dos equis ranch water']::text[]),
('indianabev', 'Flying Embers', 'Seltzer', array['flying embers']::text[]),
('indianabev', 'Fruit Smash Hard Seltzer', 'Seltzer', array['fruit smash','fruit smash hard seltzer']::text[]),
('indianabev', 'Lone River Ranch Water', 'Seltzer', array['lone river ranch water']::text[]),
('indianabev', 'Mike''s Hard Seltzer', 'Seltzer', array['mike''s','mike''s hard seltzer']::text[]),
('indianabev', 'Naked Barrel Hard Seltzer', 'Seltzer', array['naked barrel','naked barrel hard seltzer']::text[]),
('indianabev', 'Odd Side Hard Seltzer', 'Seltzer', array['odd side','odd side hard seltzer']::text[]),
('indianabev', 'Press Hard Seltzer', 'Seltzer', array['press','press hard seltzer']::text[]),
('indianabev', 'Quirk Hard Seltzer', 'Seltzer', array['quirk','quirk hard seltzer']::text[]),
('indianabev', 'Ranch Water', 'Seltzer', '{}'::text[]),
('indianabev', 'Smirnoff Hard Seltzer', 'Seltzer', array['smirnoff','smirnoff hard seltzer']::text[]),
('indianabev', 'Strainge Beast Hard Kombucha', 'Seltzer', array['strainge beast','strainge beast hard kombucha']::text[]),
('indianabev', 'SweetWater Oasis Hard Seltzer', 'Seltzer', array['sweetwater oasis','sweetwater oasis hard seltzer']::text[]),
('indianabev', 'Topo Chico Hard Seltzer', 'Seltzer', array['topo chico','topo chico hard seltzer']::text[]),
('indianabev', 'Truly Hard Seltzer', 'Seltzer', array['truly','truly hard seltzer']::text[]),
('indianabev', 'Vizzy Hard Seltzer', 'Seltzer', array['vizzy','vizzy hard seltzer']::text[]),
('indianabev', 'White Claw Hard Seltzer', 'Seltzer', array['white claw','white claw hard seltzer']::text[]),
('indianabev', 'Wild Basin Hard Seltzer', 'Seltzer', array['wild basin','wild basin hard seltzer']::text[]),
('indianabev', '3D Energy', 'Non-alc', array['3d energy']::text[]),
('indianabev', '1919 Root Beer', 'Non-alc', array['1919 root','1919 root beer']::text[]),
('indianabev', 'Abita Root Beer', 'Non-alc', array['abita root','abita root beer']::text[]),
('indianabev', 'Absopure Water', 'Non-alc', array['absopure water']::text[]),
('indianabev', 'Alani Nu', 'Non-alc', array['alani nu']::text[]),
('indianabev', 'Athletic Brewing', 'Non-alc', array['athletic','athletic brewing']::text[]),
('indianabev', 'BioSteel', 'Non-alc', array['biosteel']::text[]),
('indianabev', 'Buckler 0.0', 'Non-alc', array['buckler 0.0']::text[]),
('indianabev', 'Clearly Canadian', 'Non-alc', array['clearly canadian']::text[]),
('indianabev', 'Henry Weinhard''s Gourmet Soda', 'Non-alc', array['henry weinhard''s gourmet soda']::text[]),
('indianabev', 'Hostess Iced Lattes', 'Non-alc', array['hostess iced lattes']::text[]),
('indianabev', 'Kaliber', 'Non-alc', array['kaliber']::text[]),
('indianabev', 'Karma Water', 'Non-alc', array['karma water']::text[]),
('indianabev', 'La Colombe Coffee', 'Non-alc', array['la colombe coffee']::text[]),
('indianabev', 'Lagunitas Hoppy Refresher', 'Non-alc', array['lagunitas hoppy refresher']::text[]),
('indianabev', 'Morning Wood Bloody Mary', 'Non-alc', array['morning wood bloody mary']::text[]),
('indianabev', 'Prime Energy', 'Non-alc', array['prime energy']::text[]),
('indianabev', 'Prime Hydration', 'Non-alc', array['prime hydration']::text[]),
('indianabev', 'Revitalyte', 'Non-alc', array['revitalyte']::text[]),
('indianabev', 'Ryse Fuel', 'Non-alc', array['ryse fuel']::text[]),
('indianabev', 'Sierra Nevada Hop Splash', 'Non-alc', array['sierra nevada hop splash']::text[]),
('indianabev', 'Sprecher Soda', 'Non-alc', array['sprecher soda']::text[]),
('indianabev', 'Zoa Energy', 'Non-alc', array['zoa energy']::text[])
on conflict (partner, lower(name)) do update set category = excluded.category, aliases = excluded.aliases;
